# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"

platform :ios do

  lane :development_rinkeby_beta do
    update_code_signing_settings(
      use_automatic_signing: true,
      path: "Multisig.xcodeproj"
    )
    gym(
      workspace: "Multisig.xcworkspace",
      scheme: "Multisig - Development Rinkeby",
      include_symbols: true,
      include_bitcode: true
    )
    upload_to_testflight
  end
  
end
